### ISSUE TITLE
Frontend programmed with Angular 6 + Bootstrap 4 + Typescript : source project for enhancement

### ISSUE THREAD

**Issue by yboujraf** [Pepelux/SIP-Firewall#3]
Dear @Pepelux 

Would you like to share the angular + bootstrap source project ?

Best Regards,

**Comment by Pepelux** [comment]
Hi!

I have uploaded the source code of Angular and APIRest. 

However, it is better to use the module secfilter for Kamailio that I've programmed recently (https://www.kamailio.org/docs/modules/devel/modules/secfilter.html). It is bassed on this project but integred in Kamailio

Regards

**Comment by yboujraf** [comment]
Dear @Pepelux 

I hope you are well.

Google doesn't support Angular 6 anymore.
Do you think you will move to Angular 12 ?

Best regards,
